In [1]:
# 1. Import the numpy package under the name `np`
# 2. Print the numpy version
import numpy as np
np._version_


AttributeError: module 'numpy' has no attribute '_version_'

In [2]:
# 3. Create a vector of zeros with the size 10
import numpy as np
zeroVector = np.zeros(10)
print(zeroVector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#  4. How to find the memory size of any array
x = np.array([1, 2, 5, 100])
"print("Memory size of the array is: ", x.size * x.itemsize)
    

SyntaxError: unterminated string literal (detected at line 3) (3256933133.py, line 3)

In [4]:
#  4. How to find the memory size of any array
x = np.array([1, 2, 5, 100])
print("Memory size of the array is: ", x.size * x.itemsize)


Memory size of the array is:  16


In [5]:
# 5. How to get the documentation of the numpy add function from the IPython console?
import numpy as np
print(np.info(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
# 6. Create a vector of zeros with the size 10 but the fifth value which is 1
vector = np.zeros(10)
vector[4] = 1


In [7]:
# 7. Create a vector with values ranging from 10 to 49
# hint: arange
np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
# 8. Reverse a vector (first element becomes last)
reversedVector = np.arange(10,50)
reversedVector[::-1]\


SyntaxError: incomplete input (674079099.py, line 3)

In [10]:
# 8. Reverse a vector (first element becomes last)
reversedVector = np.arange(10,50)
reversedVector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [11]:
# Create a 3x3 matrix with values ranging from 0 to 8
matrix1 = np.arange(0,9)
matrix1.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
# 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] 
import numpy as np
print(np.nonzero([1, 2, 0, 0, 4, 0])


SyntaxError: incomplete input (2125538380.py, line 3)

In [13]:
# 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] 
import numpy as np
print(np.nonzero([1, 2, 0, 0, 4, 0]))


(array([0, 1, 4], dtype=int64),)


In [14]:
# 11. Create a 3x3 identity matrix (★☆☆)
# hint: the best numpy documentation is in the scipy website :)
np.identity(3)



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# 12. Create a 3x3x3 array with random values
np.random.random((3, 3, 3))


array([[[0.78170704, 0.43357993, 0.87200119],
        [0.90574667, 0.99471825, 0.80224663],
        [0.52903417, 0.98784813, 0.40662573]],

       [[0.49274968, 0.15742508, 0.53366278],
        [0.12217037, 0.26068395, 0.1682791 ],
        [0.37298887, 0.88281991, 0.77844943]],

       [[0.06536545, 0.33523431, 0.18271431],
        [0.80305423, 0.65352814, 0.46151903],
        [0.20448628, 0.82117114, 0.76792561]]])

In [16]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values
# hint: a.min,a.max
randomArray = np.random.random((10,10))
# minimum value
np.min(randomArray)
# maximum values
np.max(randomArray)


0.9883918551684364

In [17]:
# 14. Create a random vector of size 30 and find the mean value
# hint: a.mean
vector = np.random.random((5,6))

# mean values of matrix
np.mean(vector)


0.49139185760166515

In [18]:
#  Create a 2d array with 1 on the border and 0 inside
# hint: ones()
# hint2: for an array a, which elements are chosen by a[1:-1] ?
array = np.ones((5,5))
array[1:4, 1:4] = 0 	
